const catalog=[
 {title:'Billboards',number:'01',copy:'Large-format campaigns, structural work, printing and installation.',slides:['billboard-01.jpg','billboard-02.jpg','billboard-03.jpg'],sourceDir:'portfolio_clean'},
 {title:'Industrial label printing',number:'02',copy:'Custom labeling services with different shapes, sizes and finishes, presented in KW\'s company profile.',slides:['label-printing.jpg'],source:true},
 {title:'Signage & fabrication',number:'03',copy:'Indoor and outdoor signage, acrylic, lightboxes and custom builds.',slides:['signage-33-02.jpg','signage-31-01.jpg','signage-32-01.jpg','signage-27-01.jpg']},
 {title:'DOOH advertising',number:'04',copy:'Digital out-of-home solutions designed for high-visibility urban environments.',slides:['dooh-24-01.jpg','dooh-21-01.jpg','dooh-22-01.jpg']},
 {title:'Wall wraps',number:'05',copy:'Building-scale graphics that turn architecture into brand surface.',slides:['wall-wrap-20-01.jpg','wall-wrap-19-01.jpg']},
 {title:'Vehicle & event branding',number:'06',copy:'Fleet graphics, wraps, flags, banners and promotional display systems.',slides:['vehicle-26-01.jpg','vehicle-26-02.jpg','banners-25-02.jpg','signage-27-01.jpg']}
];
const team=[
 ['kahsay-woldesilassie.png','Kahsay Woldesilassie','Founder & General Manager',true],['rania-ibrahim.png','Rania Ibrahim, MD','General Manager'],['helina-legesse.png','Helina Legesse','Marketing & Operational Manager'],['sirak-wendemagegn.png','Sirak Wendemagegn','Human Resource & Production Manager'],['dawit-worku.png','Dawit Worku','Administration & Finance'],['solomon-desalegn.png','Solomon Desalegn, MD','Marketing Director'],['helina-gizachew.png','Helina Gizachew','Account Executive'],['helina-maregie.png','Helina Maregie','Accountant'],['mekdes-hailu.png','Mekdes Hailu','Graphic Designer'],['meki-shewangizaw.png','Meki Shewangizaw','Graphic Designer']
];
const portfolioPath=file=>`assets/images/portfolio/${file}`;const sourcePath=file=>`assets/images/source_clean/${file}`;const catalogImagePath=item=>item.source?sourcePath(item.slides[0]):(item.sourceDir?`assets/images/${item.sourceDir}/${item.slides[0]}`:portfolioPath(item.slides[0]));const catalogSlidePath=(item,file)=>item.source?sourcePath(file):(item.sourceDir?`assets/images/${item.sourceDir}/${file}`:portfolioPath(file));
function renderCatalog(){const grid=document.getElementById('catalog-grid');if(!grid)return;grid.innerHTML='';catalog.forEach(item=>{const card=document.createElement('article');card.className='catalog-card';const first=catalogImagePath(item);card.innerHTML=`<div class="catalog-media" aria-live="polite"><img src="${first}" alt="KW ${item.title} project" loading="lazy"><button class="catalog-arrow prev" type="button" aria-label="Previous ${item.title} image">←</button><button class="catalog-arrow next" type="button" aria-label="Next ${item.title} image">→</button><div class="catalog-overlay"></div><div class="catalog-meta"><span>${item.number} / ${item.title}</span><span class="catalog-count">1 / ${item.slides.length}</span></div></div><div class="catalog-copy"><h3>${item.title}</h3><p>${item.copy}</p></div>`;grid.appendChild(card);setupCarousel(card,item)})}
function setupCarousel(card,item){let current=0,touchStartX=0,touchStartY=0;const img=card.querySelector('img'),count=card.querySelector('.catalog-count');const go=direction=>{if(item.slides.length<2)return;current=(current+direction+item.slides.length)%item.slides.length;img.classList.remove('slide-next','slide-prev');void img.offsetWidth;img.classList.add(direction>0?'slide-next':'slide-prev');img.src=catalogSlidePath(item,item.slides[current]);img.alt=`KW ${item.title} project ${current+1}`;count.textContent=`${current+1} / ${item.slides.length}`};card.querySelector('.prev').addEventListener('click',()=>go(-1));card.querySelector('.next').addEventListener('click',()=>go(1));if(item.slides.length<2)card.querySelectorAll('.catalog-arrow').forEach(b=>b.hidden=true);card.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX;touchStartY=e.changedTouches[0].clientY},{passive:true});card.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))go(dx<0?1:-1)},{passive:true})}
function renderTeam(){const grid=document.getElementById('team-grid');if(!grid)return;grid.innerHTML='';team.forEach(m=>{const card=document.createElement('article');card.className='team-card'+(m[3]?' featured':'');card.innerHTML=`<div class="team-photo"><div class="team-oval"><img src="assets/images/team/processed/${m[0]}" alt="${m[1]}, ${m[2]}" loading="lazy"></div></div><div class="team-meta"><h3>${m[1]}</h3><p>${m[2]}</p></div>`;grid.appendChild(card)})}
renderCatalog();renderTeam();
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');if(menu){menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',open);document.body.classList.toggle('lock',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.classList.remove('lock')}))}
const header=document.getElementById('header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>20),{passive:true});
const quoteForm=document.getElementById('quote-form');if(quoteForm)quoteForm.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent('Quote request — '+(d.get('company')||d.get('name')));const body=encodeURIComponent(`Name: ${d.get('name')}\nCompany: ${d.get('company')}\nEmail: ${d.get('email')}\nPhone: ${d.get('phone')}\nService: ${d.get('service')}\n\nProject details:\n${d.get('message')}`);window.location.href=`mailto:helina@kwadvertising.org?subject=${subject}&body=${body}`});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
